// Generated by devimg. Do not edit by hand.
export const DEVIMG_MANIFEST = {
  version: 1,
  generated_at: "unix:1777758560",
  config_hash: "blake3:91205b8394f1fe1d62809d363f88d4f015680b1f3de57805d0eadcd629240c00",
  sources: [
    {
      source_path: "public/projects/accesstrace-overview.png",
      source_hash: "blake3:f966621f26d4f9b65d03ae8df992bab373ed0ef8d05beff2303a9af6df9e62a3",
      source_width: 1280,
      source_height: 1136,
      source_bytes: 151031,
      variants: [
        {
          src: "/images/generated/projects/accesstrace-overview.project-banner.1200.2e980c09f37e.jpeg",
          output_path:
            "public/images/generated/projects/accesstrace-overview.project-banner.1200.2e980c09f37e.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 101724,
          hash: "blake3:2e980c09f37ebe20e7bfa8e717e0dd25aa3dc08cd94b8a71d4249256652054ce"
        },
        {
          src: "/images/generated/projects/accesstrace-overview.project-card.640.99197950f285.jpeg",
          output_path:
            "public/images/generated/projects/accesstrace-overview.project-card.640.99197950f285.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 39996,
          hash: "blake3:99197950f285d1c60c88a4c755fc8486b3c99bcb8b277a99123733850b72dcfc"
        }
      ]
    },
    {
      source_path: "public/projects/cli_tools.png",
      source_hash: "blake3:4dffeaec821cadd3486c8585ce13d0fa1729ebf3c449403c9c3814409ff76b47",
      source_width: 1731,
      source_height: 909,
      source_bytes: 1361650,
      variants: [
        {
          src: "/images/generated/projects/cli_tools.project-banner.1200.357fa291d080.jpeg",
          output_path:
            "public/images/generated/projects/cli_tools.project-banner.1200.357fa291d080.jpeg",
          preset: "project-banner",
          fit: "contain",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 91518,
          hash: "blake3:357fa291d08066268b5c97cd9c46291054a684fd724cb276276f105e52741741"
        },
        {
          src: "/images/generated/projects/cli_tools.project-card.640.bb144ce19644.jpeg",
          output_path:
            "public/images/generated/projects/cli_tools.project-card.640.bb144ce19644.jpeg",
          preset: "project-card",
          fit: "contain",
          width: 640,
          height: 336,
          format: "jpeg",
          bytes: 33233,
          hash: "blake3:bb144ce19644068289ecd58847c30beb1834823cfb03808488fc81381bf2ea11"
        }
      ]
    },
    {
      source_path: "public/projects/website.webp",
      source_hash: "blake3:afa14f6f21d5d2bb7a5660eee7005ce244ef8be052ed19ebb40d8bb9e3291fa6",
      source_width: 2796,
      source_height: 1584,
      source_bytes: 108584,
      variants: [
        {
          src: "/images/generated/projects/website.project-banner.1200.2c72d6802a9e.jpeg",
          output_path:
            "public/images/generated/projects/website.project-banner.1200.2c72d6802a9e.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 77553,
          hash: "blake3:2c72d6802a9e8ab0b1acb95e71c2d7332a196d2fe103100aeaf8b83a5eadb8e2"
        },
        {
          src: "/images/generated/projects/website.project-card.640.88dea3f9f53b.jpeg",
          output_path:
            "public/images/generated/projects/website.project-card.640.88dea3f9f53b.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 30658,
          hash: "blake3:88dea3f9f53b2dc609a5c0849805fcfbba76a82676f7bd66db5ce03deaffe99e"
        }
      ]
    }
  ]
} as const
