// Generated by devimg. Do not edit by hand.
export const DEVIMG_MANIFEST = {
  version: 1,
  generated_at: "unix:1777820713",
  config_hash: "blake3:d8416da24d8da50f161a9ed6f85e3254cc08ea74c1fcccb293fa32d728a6fd65",
  sources: [
    {
      source_path: "public/projects/accesstrace-overview.png",
      source_hash: "blake3:f966621f26d4f9b65d03ae8df992bab373ed0ef8d05beff2303a9af6df9e62a3",
      source_width: 1280,
      source_height: 1136,
      source_bytes: 151031,
      variants: [
        {
          src: "/images/generated/projects/accesstrace-overview.project-banner.1200.a5cc41e55e3a.jpeg",
          output_path:
            "public/images/generated/projects/accesstrace-overview.project-banner.1200.a5cc41e55e3a.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 128986,
          hash: "blake3:a5cc41e55e3acc325d8cc65fa02d3f5d14a9c5a4ef2b050390076b2cfe9da175"
        },
        {
          src: "/images/generated/projects/accesstrace-overview.project-card.640.e21ca73fb0f9.jpeg",
          output_path:
            "public/images/generated/projects/accesstrace-overview.project-card.640.e21ca73fb0f9.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 51018,
          hash: "blake3:e21ca73fb0f9c547b0d99e8f5bb4a3f7e00ea142bf94bac27ee6a0c19f91ce60"
        }
      ]
    },
    {
      source_path: "public/projects/cli_tools.png",
      source_hash: "blake3:4dffeaec821cadd3486c8585ce13d0fa1729ebf3c449403c9c3814409ff76b47",
      source_width: 1731,
      source_height: 909,
      source_bytes: 1361650,
      variants: [
        {
          src: "/images/generated/projects/cli_tools.project-banner.1200.cafd458c426a.jpeg",
          output_path:
            "public/images/generated/projects/cli_tools.project-banner.1200.cafd458c426a.jpeg",
          preset: "project-banner",
          fit: "contain",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 121517,
          hash: "blake3:cafd458c426aaecb2c7ea39c77aff27da29df6003e6f164841fc8a2d42d1e420"
        },
        {
          src: "/images/generated/projects/cli_tools.project-card.640.5b8292e81375.jpeg",
          output_path:
            "public/images/generated/projects/cli_tools.project-card.640.5b8292e81375.jpeg",
          preset: "project-card",
          fit: "contain",
          width: 640,
          height: 336,
          format: "jpeg",
          bytes: 44295,
          hash: "blake3:5b8292e813754534cb64304685954447980f1aaf4db860fcf7c1f017aaced325"
        }
      ]
    },
    {
      source_path: "public/projects/devimg.png",
      source_hash: "blake3:fa0d5ad122cf7b25913ef3643651b1804e6463f894f689791c95540318144be4",
      source_width: 1731,
      source_height: 909,
      source_bytes: 1627787,
      variants: [
        {
          src: "/images/generated/projects/devimg.project-banner.1200.4bffb451e10d.jpeg",
          output_path:
            "public/images/generated/projects/devimg.project-banner.1200.4bffb451e10d.jpeg",
          preset: "project-banner",
          fit: "contain",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 195673,
          hash: "blake3:4bffb451e10d67db44ac7a1cd5bbb2e2cd74906a74c118b831d40bd03b5a0b71"
        },
        {
          src: "/images/generated/projects/devimg.project-card.640.1a31a13c61b7.jpeg",
          output_path: "public/images/generated/projects/devimg.project-card.640.1a31a13c61b7.jpeg",
          preset: "project-card",
          fit: "contain",
          width: 640,
          height: 336,
          format: "jpeg",
          bytes: 68327,
          hash: "blake3:1a31a13c61b7be9e47703d8b46a23ece7dc7b1ff629c421b2e5e3f62afb93a2a"
        }
      ]
    },
    {
      source_path: "public/projects/website.webp",
      source_hash: "blake3:afa14f6f21d5d2bb7a5660eee7005ce244ef8be052ed19ebb40d8bb9e3291fa6",
      source_width: 2796,
      source_height: 1584,
      source_bytes: 108584,
      variants: [
        {
          src: "/images/generated/projects/website.project-banner.1200.8fb712153b69.jpeg",
          output_path:
            "public/images/generated/projects/website.project-banner.1200.8fb712153b69.jpeg",
          preset: "project-banner",
          fit: "cover",
          width: 1200,
          height: 630,
          format: "jpeg",
          bytes: 96980,
          hash: "blake3:8fb712153b69538eb5f815b506bdcf9c76349cc74bd77d57ba05e35d4f13cc01"
        },
        {
          src: "/images/generated/projects/website.project-card.640.4702e7ceb58e.jpeg",
          output_path:
            "public/images/generated/projects/website.project-card.640.4702e7ceb58e.jpeg",
          preset: "project-card",
          fit: "cover",
          width: 640,
          height: 360,
          format: "jpeg",
          bytes: 38785,
          hash: "blake3:4702e7ceb58eabfbcc15cca9adf812892320d5d914927fc29e3fc31f1d599cd6"
        }
      ]
    }
  ]
} as const
